### ISSUE TITLE
An error occurred creating the sample dataset

### ISSUE THREAD

**Issue by BYR-HZ** [DiTEC-project/gnn-pressure-estimation#1]
Bro,There was an error when I ran the scenegenv7.py,"epynet.epanet2.ENtoolkitError: Error 223: not enough nodes in network"

**Comment by BYR-HZ** [comment]
Could you please send me some datasets that you have generated?such as :10k_p_EPYNET_n_GEN-09 Oosterbeek_03022023.zip , Thank you very much！  yurenbian@outlook.com

**Comment by sugandhrise** [comment]
Did you get any reply? You might want to fix the paths in the code but you might get stuck at the next step. I have opened up a ticket for that.

**Comment by cuongth95** [comment]
> Bro,There was an error when I ran the scenegenv7.py,"epynet.epanet2.ENtoolkitError: Error 223: not enough nodes in network"

Hallo BYR-HZ,
Sorry for the late reply. 
Please take a snapshot of your terminal and provide me with more information, such as what INP file you tried (if available).
I suspect that the INP file has trouble. I suggest you open it using EPANET and simulate it once. 

Cheers

**Comment by cuongth95** [comment]
> Could you please send me some datasets that you have generated?such as :10k_p_EPYNET_n_GEN-09 Oosterbeek_03022023.zip , Thank you very much！ [yurenbian@outlook.com](mailto:yurenbian@outlook.com)

We will share the simulated datasets of other networks very soon. However, Oosterbeek is unavailable for public use. 

Cheers.
